version: '3'
services:
  backend:
    command: npm run watch
    stdin_open: true
    ports:
      - 4000:4000
  frontend:
    command: npm run start
    stdin_open: true
    ports:
      - "3000:3000"