version: '3'
services:
  backend:
    command: npm run watch
    stdin_open: true
    volumes:
      - ./../2020-11-wns-paris-groupe1-projet-back
    ports:
      - ${API_PORT}:4000
    environment:
      - NODE_ENV=development
      - TYPEORM_LOGGING=true
  frontend:
    command: npm run start
    stdin_open: true
    volumes:
      - ./app
    ports:
      - ${WEB_CLIENT_PORT}:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_API_BASE_URL=http://localhost:${API_PORT}